sudo: required # this is to give root user access
services:
  - docker # this is telling to install docker

before_install:
  # -t for tag so that we can build image with tag and we can refer tag
  # we can put any name instead of jeevandeepsingh/docker-react for tag because we will run this inside a new process for travis
  - docker build -t jeevandeepsingh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jeevandeepsingh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-539478032043"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"